config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "devise/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  post '/stats' => 'game#update_stats', as: "stats"
  get 'welcome/index' => 'welcome#index', as: "unauth"
  get 'dashboard/leaderboard'
  get 'game/index' => 'game#index', as: "game"
  get 'game/guest_game' => 'game#guest_game', as: "guest_game"
  get 'players/:id' => 'players#show', as: "player"

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= link_to "Login", new_user_session_path, :class => "button" %>
<%= link_to "Sign Up", new_user_registration_path, :class => "button" %>
<%= link_to "Play as Guest", guest_game_path, :class => "button" %>

app/views/welcome/temp.html.erb
<% if user_signed_in? %>
	<p>Logged in as <strong><%= current_user.email %></strong>.</p>
<% end %>

<% if user_signed_in? %>
	<div class="button">Ranked Game</div>
<% else %>
	<div class="button">Play as Guest</div>
<% end %>

<div class="row">
  <div class="col-sm-4"></div>
    <%= render partial: "dashboard/leaderboard"%>